/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AirdropRouteImport } from './routes/airdrop'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as GamingRouteImport } from './routes/gaming'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as GamesGameRouteImport } from './routes/games.$game'
import { Route as ApiPublicInstagramWebhookRouteImport } from './routes/api/public/instagram/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AirdropRoute = AirdropRouteImport.update({
  id: '/airdrop',
  path: '/airdrop',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const GamingRoute = GamingRouteImport.update({
  id: '/gaming',
  path: '/gaming',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameRoute = GamesGameRouteImport.update({
  id: '/games/$game',
  path: '/games/$game',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInstagramWebhookRoute =
  ApiPublicInstagramWebhookRouteImport.update({
    id: '/api/public/instagram/webhook',
    path: '/api/public/instagram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/airdrop': typeof AirdropRoute
  '/announcements': typeof AnnouncementsRoute
  '/gaming': typeof GamingRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profile': typeof ProfileRoute
  '/referrals': typeof ReferralsRoute
  '/tasks': typeof TasksRoute
  '/games/$game': typeof GamesGameRoute
  '/api/public/instagram/webhook': typeof ApiPublicInstagramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/airdrop': typeof AirdropRoute
  '/announcements': typeof AnnouncementsRoute
  '/gaming': typeof GamingRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profile': typeof ProfileRoute
  '/referrals': typeof ReferralsRoute
  '/tasks': typeof TasksRoute
  '/games/$game': typeof GamesGameRoute
  '/api/public/instagram/webhook': typeof ApiPublicInstagramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/airdrop': typeof AirdropRoute
  '/announcements': typeof AnnouncementsRoute
  '/gaming': typeof GamingRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profile': typeof ProfileRoute
  '/referrals': typeof ReferralsRoute
  '/tasks': typeof TasksRoute
  '/games/$game': typeof GamesGameRoute
  '/api/public/instagram/webhook': typeof ApiPublicInstagramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/airdrop'
    | '/announcements'
    | '/gaming'
    | '/leaderboard'
    | '/profile'
    | '/referrals'
    | '/tasks'
    | '/games/$game'
    | '/api/public/instagram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/airdrop'
    | '/announcements'
    | '/gaming'
    | '/leaderboard'
    | '/profile'
    | '/referrals'
    | '/tasks'
    | '/games/$game'
    | '/api/public/instagram/webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/airdrop'
    | '/announcements'
    | '/gaming'
    | '/leaderboard'
    | '/profile'
    | '/referrals'
    | '/tasks'
    | '/games/$game'
    | '/api/public/instagram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AirdropRoute: typeof AirdropRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  GamingRoute: typeof GamingRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ProfileRoute: typeof ProfileRoute
  ReferralsRoute: typeof ReferralsRoute
  TasksRoute: typeof TasksRoute
  GamesGameRoute: typeof GamesGameRoute
  ApiPublicInstagramWebhookRoute: typeof ApiPublicInstagramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airdrop': {
      id: '/airdrop'
      path: '/airdrop'
      fullPath: '/airdrop'
      preLoaderRoute: typeof AirdropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gaming': {
      id: '/gaming'
      path: '/gaming'
      fullPath: '/gaming'
      preLoaderRoute: typeof GamingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$game': {
      id: '/games/$game'
      path: '/games/$game'
      fullPath: '/games/$game'
      preLoaderRoute: typeof GamesGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/instagram/webhook': {
      id: '/api/public/instagram/webhook'
      path: '/api/public/instagram/webhook'
      fullPath: '/api/public/instagram/webhook'
      preLoaderRoute: typeof ApiPublicInstagramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AirdropRoute: AirdropRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  GamingRoute: GamingRoute,
  LeaderboardRoute: LeaderboardRoute,
  ProfileRoute: ProfileRoute,
  ReferralsRoute: ReferralsRoute,
  TasksRoute: TasksRoute,
  GamesGameRoute: GamesGameRoute,
  ApiPublicInstagramWebhookRoute: ApiPublicInstagramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
